apiVersion: v1
kind: Pod
metadata:
  name: init-pod
  labels:
    name: init-pod
  namespace: jimyag
spec:
  containers:
    - name: init-pod
      image: busybox:1.28
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
      ports:
        - containerPort: 80
      command: ["sh", "-c", "echo The app is running! && sleep 31536000"]
      volumeMounts:
        - name: empty-volume
          mountPath: /data
  initContainers:
    - name: init-1
      image: busybox:1.28
      command: ["sh", "-c", "touch /data/init-1 && echo 'init-1' && date"]
      volumeMounts:
        - name: empty-volume
          mountPath: /data
    - name: init-2
      image: busybox:1.28
      command: ["sh", "-c", "touch /data/init-2 && echo 'init-2' && date"]
      volumeMounts:
        - name: empty-volume
          mountPath: /data

  volumes:
    - name: empty-volume
      emptyDir: {}
