kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: jimyag-scheduler
rules:
  - apiGroups:
      - "*"
    resources:
      - "*"
    verbs:
      - "*"
  - nonResourceURLs:
      - "*"
    verbs:
      - "*"
