apiVersion: v1
kind: ConfigMap
metadata:
  name: jimyag-scheduler-config
  namespace: kube-system
data:
  jimyag-scheduler-config.yaml: |
    apiVersion: kubescheduler.config.k8s.io/v1
    kind: KubeSchedulerConfiguration
    profiles:
      - schedulerName: jimyag-scheduler
        plugins:
          filter:
            enabled:
            - name: JimyagCustom
          postFilter:
            enabled:
            - name: JimyagCustom
    leaderElection:
      leaderElect: false
