apiVersion: apps/v1
kind: Deployment
metadata:
  name: jimyag-scheduler
  namespace: kube-system
  labels:
    component: jimyag-scheduler
spec:
  replicas: 1
  selector:
    matchLabels:
      component: jimyag-scheduler
  template:
    metadata:
      labels:
        component: jimyag-scheduler
    spec:
      serviceAccount: jimyag-scheduler
      priorityClassName: system-cluster-critical
      volumes:
        - name: scheduler-config
          configMap:
            name: jimyag-scheduler
      containers:
        - name: scheduler
          image: registry.i.jimyag.com/k8sdev/scheduler:2024-08-06-23-40-59
          imagePullPolicy: IfNotPresent
          args:
            - /app/scheduler
            - --config=/etc/kubernetes/scheduler-config.yaml
          resources:
            requests:
              cpu: "500m"
              memory: "640Mi"
            limits:
              cpu: "1000m"
              memory: "1280Mi"
          volumeMounts:
            - name: scheduler-config
              mountPath: /etc/kubernetes
