# ClusterRoleBinding: 将 system:kube-scheduler 角色绑定到 jimyag-scheduler 服务账户。
# system:kube-scheduler: 提供与默认 Kubernetes 调度器相同的权限，使自定义调度器能够执行调度相关的操作。

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: jimyag-scheduler-as-kube-scheduler
subjects:
  - kind: ServiceAccount
    name: jimyag-scheduler
    namespace: kube-system
roleRef:
  kind: ClusterRole
  name: system:kube-scheduler
  apiGroup: rbac.authorization.k8s.io
