# ClusterRoleBinding: 将 system:volume-scheduler 角色绑定到 jimyag-scheduler 服务账户。
# system:volume-scheduler: 提供调度与存储卷相关的权限，这对于需要与持久卷交互的调度器很重要。
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: jimyag-scheduler-as-volume-scheduler
subjects:
  - kind: ServiceAccount
    name: jimyag-scheduler
    namespace: kube-system
roleRef:
  kind: ClusterRole
  name: system:volume-scheduler
  apiGroup: rbac.authorization.k8s.io
