apiVersion: v1
kind: LimitRange
metadata:
  name: limit-range
  namespace: jimyag
spec:
  limits:
    - max:
        memory: 1024Mi
        cpu: 1000m
      min:
        memory: 128Mi
        cpu: 100m
      default:
        memory: 512Mi
        cpu: 500m
      defaultRequest:
        memory: 256Mi
        cpu: 250m
      maxLimitRequestRatio:
        memory: 100Mi
        cpu: 1000m
      type: Container

    - max:
        memory: 1024Mi
        cpu: 1000m
      min:
        memory: 128Mi
        cpu: 100m
      default:
        memory: 512Mi
        cpu: 500m
      defaultRequest:
        memory: 256Mi
        cpu: 250m
      maxLimitRequestRatio:
        memory: 100Mi
        cpu: 1000m
      type: Pod

    - max:
        memory: 1024Mi
        cpu: 1000m
      min:
        memory: 128Mi
        cpu: 100m
      default:
        memory: 512Mi
        cpu: 500m
      defaultRequest:
        memory: 256Mi
        cpu: 250m
      maxLimitRequestRatio:
        memory: 100Mi
        cpu: 1000m
      type: PersistentVolumeClaim
#  https://github.com/kubernetes/kubernetes/blob/3d0594d4d92653fcefea0b91363f473ae457c6b8/pkg/apis/core/types.go#L5571
